env:
  global:
    - COMMIT_AUTHOR_EMAIL: mahdi_1373@yahoo.com

dist: trusty
language: python
python: '3.6'

branches:
  only:
    - master
    - hotfix
    - develop
    - "/^v.*beta.*$/"
    - "/^v.*alpha.*$/"

addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
      - libpq-dev
  postgresql: 9.5
  ssh_known_hosts: 116.203.119.119

services:
  - redis-server

install: ".travis/install.sh"

script: coverage run --source emerald $(which nosetests)

after_success:
  - if [[ $TRAVIS_BRANCH == 'develop' ]]; then .travis/wiki.sh ; fi

before_deploy:
  - openssl aes-256-cbc -K $encrypted_11587ee85302_key -iv $encrypted_11587ee85302_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: scp build/ "$SSH_USER@$SSH_HOST:~/stawallet/build/"
#  on:
#    branch: master
