env:
  global:
    - COMMIT_AUTHOR_EMAIL: mahdi_1373@yahoo.com
    - secure: zePL5N1XRfSMgzi5Hu49AvTh4VVj+CtuDfuCGZezZBWo9zE22ttxKC7evpsWBye9mRwQVIHihO1ampXxxZiDnbt7sOe3mnqUuUgIDkGR+UYqoZuJccWwxXLQizUeUt9Y2RlmVmiOt87ksh2sSXXwAoM4dwxbVitjGqgwRSMqjrXhkbRakOTIOfJh7m3PXgdZDEesH5BTYVC8gmwQ06jzah/lUT/SRl1/vx7duNVnDNN3lO2qlqw/Q1/+gM3B8aaOOC3OpSPT5mu2QUbRVZhFfST0IDm7sthu1VbazMvaTrmp+TEAZi3NM9VjpZJZBNEGoCXrS2O8bUqNWbj/zjLUOfXovLXnsof0fChiABzje10nCeLyqnQOX8LUZJ7lcdky00Xi7Q9c0HBpBL2biOgGwjK7DyxtkD7QhUb1tsY07jz6Dc+30I9EBT4SSCZAdewaH9fezGrT36YDUVz/cNOCMgIOCwMc5r6DvOIE8NSv9Lm5jCeRdBWvTDLXoglCMWroHhWtKc5OH+ImhU+CtAZeLHvkELh8xVonWGQbXN+wySOYxQJBj3s4LIVSIq1qi9OAKibj8epE0Oyp/IasH/HghADJtzrNwxBMj611o8wfxaWHMXu5K4cPHCv43n2AcfRjKvj/OKKfPfjUflho9+eFmHiTJZ7Cw2Z6kAbw4yjLfi8=
    - secure: JmBef3voGdEVgODTIGykDE6s/SdUNqVEjMAuOoO0y/+v9X4nxetPxxp0MWWg0PSVqLHaZhCmVB5phYLdb9WxQe/03eUwrzjKgpJLA07IOvuJXA1SHSXOmsSJxO4TJ1bUhrKAMU3c+01bFg/oKrgT+KGu/r4bOPtIY2f6LBQCvYMZjv3KdYDFKCprc8xUzyNnbeQOBTNsIr6RVYAhyeJfQGEa4ga2Tt4tM8xykx/OGtRMgvwNXxEUh1NOldtq2szb4NeaAr8ukwZmZSY8OmeCDD5mZevmcFLwsU0vgT4Dv6rdzonl0NVYg3M6+P4/vtaoRIeGaLxg0k0HBsO/dgLGjhdH5eLsJ0dLRIc/Wy0HJzCpYWQYRpOJ9mcXR1KMlsxo8wq4IINXvqXPg7akUVmYAoHlC/TR6AYj7GbSIhcUoEYjjnVtjw44yE44KRhFqBDWCWP3aPA/YDshfxn+ooq0Zh6206nEUOxAAVHWlMPRHzFKcoYM4DDn08Ow/19BEV3tHG1pKL16FkCE9YW7KhPEcpmXQWYuhp53GRaZrog7W15Lul78ao61eSskQh+G+8nqDNVQ+bi9MYnlgarbuB3ojpOYHHd8njsg4cwOC+2W6Myu6X06Zc0UvBskeENCDlI/I56y/Hb/KtgK9MgUoT9YeNpj/bpLgiMtTfJhpPyG/Po=
    - secure: ARHnLYaSuHhZPhxe/nb6pbRVw5vPCWSwu0/D+u0obwzs13Otc882+AWF7ePTefyPJ8+VvrSSE0Zp36EsSRPrgsYYOrbFPnvUfik+z728Dq6k8KFlI9m/04Jbl6J/IvJl/qkT5SVoa4H5yAzNiOkPk/BR67GE6Em8BHtyO0IcuP9VXuur3T710F92COTh4CaVPM97tvRRDIVHGlDP//9eqoCKLMGVXu4sbrsjJS5FCfOdDn9LfFrLY9Fc785cYfm5PVEUbU8rU7ElfixeV7uJvUFrmjGwJIJFToz1/dBWzQgVzDaeh5dXgqCfV7iw/nC4ugoykMxhIDcZGJfS5ym5qQl8EPo8bLzXFbGbjF0MRx21uwZEOj2pZb9hh/RY0mg10w6Ubz2wQ64boHOrmgoynuVRLAOm1GBPt6OoJJ+G45m0MHTm33/y2DOdufiVF1pgzX3WAsF5Yd3RtsHB5pWz7OU3//4xdAvD0ePeH1Y4Bym9DFgQo/v7URAHVhLZv32CYgzUw9joA23HTAl8Yc0zv8iwW/9ZP9/+sSUa1j0PmptmoW/+T/aVAzpOFo0eMtzU6/1WFe4ZVX3ARuJs3XkGtxTaDVQVVaoR42eyAFTsiXqVg54l0hz4kn5Gz4p2nC20dzHAzSf4WncHP5ei7BjBWF25sRR6rkdVkTp4uWjohno=
    - COMMIT=${TRAVIS_COMMIT::8}
dist: trusty
language: python
python: '3.6'
branches:
  only:
    - master
    - hotfix
    - develop
    - "/^v.*beta.*$/"
    - "/^v.*alpha.*$/"
addons:
  apt:
    sources:
      - precise-pgdg-9.5
    packages:
      - postgresql-9.5
      - postgresql-contrib-9.5
      - libpq-dev
  postgresql: 9.5
  ssh_known_hosts: 116.203.119.119
services:
  - docker
  - redis-server
install: ".travis/install.sh"
script: coverage run --source emerald $(which nosetests)
after_success:
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then .travis/wiki.sh ; fi
before_deploy:
  - openssl aes-256-cbc -K $encrypted_05c658a95df7_key -iv $encrypted_05c658a95df7_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=stacrypt/bstemerald
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
    ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
deploy:
  provider: script
  script: docker push $REPO && scp docker-compose.production.yml "$SSH_USER@$SSH_HOST:~/stemerald/docker-compose.yml" && ssh $SSH_USER@$SSH_HOST "cd stemerald/ && docker-compose up --force-recreate --build"
  on:
    branch: master
