env:
  global:
  - COMMIT_AUTHOR_EMAIL: mahdi_1373@yahoo.com
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: ZbVgVTgYg8sX+RZMBZ/c77gp8Gi/bxKow3XlhafT+2d9Do3ddj1mORk+OiG0voCb1B+WHkw7JSCBSgB3LQvUraoEQmioANCvUbl0IvgH25JSFBhhEgxooqwOI8qlR0gfmucNlR1TwnrdDDpwTDOnvL5U317yTDqSRcOXCJda2JBKiwdnXC1/F2Q4FDJrvZevgtlOGaTDi7AVAVA26HbTnrxzE4CD6oW3syKn9BSAsA4KC02CAEDV9Fz1tmTYclGS+NDnVQyEH2L5UAGGz9iU9OM5h5lUmWIJ8CjwPVNcc+ZUN7XOn6HbLC2axcRp8AEMBTSVkdEhCMxAVsMI5ooxCiWtQZnuwfRZGGt+f1UEJZKxR0nH0r0PuS4yZthmoH58FqvvYb3cNHBcgpZxwLtzSKa58UYCHwkGqiLecECHqgHRR3+pWkPU2jndn0saabpPv8Pew3BkUjbUQ1KiYKhO0ZsFmT25g5Fk1pLjEIC22AM+xy1dLl0cQtQOoK1suDK/HG58SDo2ulkbCSD1twEQZJak3nGHQBUNQ/+AmbzmYn3fwNDpDMe2cq7APi4F3mysl/qdTpVjlwgrf+M9yKgLSklEiXMsieyWZOlnH3JZc5SJ6DMhP6+J6vcCwlioqyhXqh7xqWgaLYZwDpF3zPUZ4ZXJdfrUrYtJgX4sRfDa82U=
  - secure: ZBdPJIysTFabkJGk18xoBivH5IvB/bYJb+MSthl+X9k05yZtWMJcsTf1Aorpbgr6WMemUw+QqYF8ZdmFELobnKhvk2wuoP9n/RjaYT72SJ7BedHtY/bDHMHdYhDvdH/5rl+DXw9v9LjKeAWK++W0iyuKzsKTN9cy47TJr4JYkqM6ZBJ2pT89u5AQEI9PcOuTt60NyNJe014TwazRQhAg6AXyGxQkDYn+No0J4e1PXU7TXt3RNAGuSGcZiBz8tnznUqzGLu5T2HUGUfACGuLuRNChy/dE2Y6rgzVpCBAXQyC+I+SppqKpkwMcWsid3Ncmpb0T7oSuD/o3EvXUqw70QB7VKbMDSktzTcaMOqpltaNnIhQxLuSvSJEJkHja//UsO5RUlyX0kGCktiuPzBVM4rABjC6XOk+2CTFv0iZLZW6tNgJ3GjE7xGwZPEACsWgx5xeKUNtiZo9anZUHDFcq6EYYWJiLXo940hBcxVAKboc31LRq2ZSb+mXxnQOHa/rhHcyQDdidUkVWAKGatE7/PI79BAIMMvh19pQ0D8rjJ8cc8kYO3YuygxKqDp1LSbGNlvsf6os/ZRPoWlqJGUbLw8hsxn+EYntxWd88SW4j6bZROmbPH+FWrrwG5OKg8EzcMD7Y3eVR+qdGNJmnRyANdei85pZd0+bCw8p9VsBAA40=
dist: trusty
language: python
python: '3.6'
branches:
  only:
  - master
  - hotfix
  - develop
  - "/^v.*beta.*$/"
  - "/^v.*alpha.*$/"
addons:
  apt:
    sources:
    - precise-pgdg-9.5
    packages:
    - postgresql-9.5
    - postgresql-contrib-9.5
    - libpq-dev
  postgresql: 9.5
  ssh_known_hosts: 116.203.119.119
services:
- docker
- redis-server
install: ".travis/install.sh"
script: coverage run --source emerald $(which nosetests)
before_deploy:
- openssl aes-256-cbc -K $encrypted_05c658a95df7_key -iv $encrypted_05c658a95df7_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=stacrypt/bstemerald
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
deploy:
  provider: script
  skip_cleanup: true
  script: docker push $REPO && scp docker-compose.production.yml "$SSH_USER@$SSH_HOST:~/stemerald/docker-compose.yml"
    && ssh $SSH_USER@$SSH_HOST "cd stemerald/ && docker-compose up --force-recreate
    --build -d" && .travis/wiki.sh
  on:
    branch: master
