db:
  administrative_url: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres/${DB_NAME}
  url: postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres/${DB_NAME}
  echo: false

redis:
  host: redis
  port: 6379
  password:
  db: ${REDIS_DB}

authentication:
  redis:
    host: redis
    port: 6379
    password:
    db: ${REDIS_DB}

smtp:
  host: smtp.gmail.com
  port: 587
  local_hostname: stacrypt.io
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
  tls: true
  auth: true
  ssl: false

media_storage:
  file_system_dir: %(root_path)s/data/media-storage
  base_url: http://localhost:8081/media

messaging:
  default_sender: Stemerald
  default_messenger: restfulpy.messaging.SmtpProvider
  template_dirs:
    - %(root_path)s/stemerald/templates

reset_password:
  secret: email-verification-secret
  max_age: 3600  # seconds
  url: https://stacrypt.io/reset_password

email_verification:
  secret: email-verification-secret
  max_age: 3600  # seconds
  url: https://stacrypt.io/email_verification

shaparak:
  provider: stemerald.shaparak.PayIrProvider

  pay_ir:
    api_key: ${PAY_IR_API_KEY}
    gateway_url: https://pay.ir/payment/gateway/{transactionId}
    post_redirect_url: https://stacrypt.io/apiv1/transactions/shaparak-ins/pay-irs
    result_redirect_url: https://stacrypt.io/payment_redirect

sms:
  provider: stemerald.sms.KavenegarSmsProvider

  kavenegar:
    verification_code_url: https://api.kavenegar.com/v1/${KAVEHNEGAR_API_KEY}/verify/lookup.json

oath:
  window: 3
  ocra_suite: OCRA-1:HOTP-SHA256-6:QA40-T1M
  time_interval: 60 # Seconds

mobile_phone_verification:
  template: mobile
  seed: ${PHONE_VERIFICATION_SEED}

fixed_phone_verification:
  template: fixed
  seed: ${PHONE_VERIFICATION_SEED}

trader:
  price_threshold_permille: 50
  gap: 3 # Seconds

membership:
  invitation_code_required: false
  second_factor_seed: ${SECOND_FACTOR_SEED}

stexchange:
  rpc_url: "http://116.203.31.26:8080"

stawallet:
  rest_url: "http://116.203.118.177:80"
  sync_gap: 3 # Seconds

firebase:
  server_key: ${FIREBASE_SERVER_KEY}
  service_account_key: "/var/stemerald/stacrypt-1c4dc-firebase-adminsdk-hy7hb-ad49502f48.json"

logging:

  loggers:
    default:
      handlers:
        - main
        - error
      level: debug
      formatter: default

  handlers:

    default:
      level: notset
      type: file
      max_bytes: 52428800

    console:
      type: console

    main:
      filename: ${LOG_DIR}/main.log

    error:
      level: error
      filename: ${LOG_DIR}/error.log
