version: '3.6'

services:

  postgres:
    container_name: postgres_main
    image: postgres:9
    restart: always
    environment:
      POSTGRES_DB: stemerald_db
      POSTGRES_USER: stemerald
      POSTGRES_PASSWORD: stemerald
    ports:
      - 5432:5432
    volumes:
      - stemerald_db:/var/lib/postgres/data

  redis:
    container_name: redis_main
    image: redis:latest
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "6379"

  wsgi:
    container_name: wsgi_main
    image: stacrypt/bstemerald:latest
    command: wsgi
    restart: always
    links:
      - postgres:pgdb
      - redis:redisdb
    depends_on:
      - postgres
      - redis
    environment:
      - DB_USERNAME=stemerald
      - DB_PASSWORD=stemerald
      - DB_NAME=stemerald_db
      - REDIS_DB=0
      - PAY_IR_API_KEY
      - PHONE_VERIFICATION_SEED
      - SECOND_FACTOR_SEED
    ports:
      - "80:8080"
    volumes:
      - ./stacrypt-1c4dc-firebase-adminsdk-hy7hb-ad49502f48.json:/var/stemerald/stacrypt-1c4dc-firebase-adminsdk-hy7hb-ad49502f48.json:ro
      - stemerald_logs_server:/var/log/stemerald

  worker:
    container_name: worker_main
    image: stacrypt/bstemerald:latest
    command: worker
    restart: always
    links:
      - postgres:pgdb
      - redis:redisdb
    depends_on:
      - postgres
      - redis
      - wsgi
    environment:
      - DB_USERNAME=stemerald
      - DB_PASSWORD=stemerald
      - DB_NAME=stemerald_db
      - REDIS_DB=0
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - KAVEHNEGAR_API_KEY
    volumes:
      - ./stacrypt-1c4dc-firebase-adminsdk-hy7hb-ad49502f48.json:/var/stemerald/stacrypt-1c4dc-firebase-adminsdk-hy7hb-ad49502f48.json:ro
      - stemerald_logs_worker:/var/log/stemerald

  stawallet_sync_looper:
    container_name: stawallet_sync_looper
    image: stacrypt/bstemerald:latest
    command: syncwallet
    restart: always
    links:
      - postgres:pgdb
      - redis:redisdb
    depends_on:
      - postgres
      - redis
      - wsgi
    environment:
      - DB_USERNAME=stemerald
      - DB_PASSWORD=stemerald
      - DB_NAME=stemerald_db
      - REDIS_DB=0
    volumes:
      - ./stacrypt-1c4dc-firebase-adminsdk-hy7hb-ad49502f48.json:/var/stemerald/stacrypt-1c4dc-firebase-adminsdk-hy7hb-ad49502f48.json:ro
      - stemerald_logs_worker:/var/log/stemerald

  cli:
    container_name: cli
    image: stacrypt/bstemerald:latest
    command: cli
    restart: always
    depends_on:
      - postgres
      - redis
      - wsgi
      - worker
#    volumes:
#      - /var/stemerald/postgres/master/data
#      - /var/stemerald/redis/master/lib
#      - /var/stemerald/service/log
#      - /var/stemerald/worker/log

volumes:
  stemerald_logs_server:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/logs/server

  stemerald_logs_worker:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/logs/worker

  stemerald_db:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/database
