version: '3.6'

services:

  postgres:
    container_name: postgres_main
    image: postgres:9
    restart: always
    environment:
      POSTGRES_DB: stemerald_db
      POSTGRES_USER: stemerald
      POSTGRES_PASSWORD: stemerald
#    networks:
#      stemerald_net:
#        ipv4_address: 192.168.19.44
    ports:
      - 5432:5432
#    volumes:
#      - stemerald_db:/var/lib/postgres/data

  redis:
    container_name: redis_main
    image: redis:latest
    restart: always
#    networks:
#      stemerald_net:
#        ipv4_address: 192.168.19.45
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "6379"

  wsgi:
    container_name: wsgi_main
    build:
      context: .
      dockerfile: Dockerfile
    command: wsgi
    restart: always
    links:
      - postgres:pgdb
      - redis:redisdb
    depends_on:
      - postgres
      - redis
    environment:
      DB_USERNAME: stemerald
      DB_PASSWORD: stemerald
      DB_NAME: stemerald_db
      REDIS_DB: 0
#    networks:
#      stemerald_net:
#        ipv4_address: 192.168.19.46
    ports:
      - "8080:8080"
#    volumes:
#      - stemerald_logs_server:/var/log/stemerald
#      - stemerald_config:/etc/stemerald

  worker:
    container_name: worker_main
    build:
      context: .
      dockerfile: Dockerfile
    command: worker
    restart: always
    links:
      - postgres:pgdb
      - redis:redisdb
    depends_on:
      - postgres
      - redis
      - wsgi
    environment:
      DB_USERNAME: stemerald
      DB_PASSWORD: stemerald
      DB_NAME: stemerald_db
      REDIS_DB: 0
#    networks:
#      stemerald_net:
#        ipv4_address: 192.168.19.47
#    volumes:
#      - stemerald_logs_worker:/var/log/stemerald
#      - stemerald_config:/etc/stemerald


  cli:
    container_name: cli
    build:
      context: .
      dockerfile: Dockerfile
    command: cli
    restart: always
    depends_on:
      - postgres
      - redis
      - wsgi
      - worker
#    networks:
#      stemerald_net:
#        ipv4_address: 192.168.19.48
#    volumes:
#      - /var/stemerald/postgres/master/data
#      - /var/stemerald/redis/master/lib
#      - /var/stemerald/service/log
#      - /var/stemerald/worker/log

#networks:
#  stemerald_net:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.19.0/24

volumes:
  stemerald_config:

#  stemerald_logs_server:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /mnt/logs/server
#
#  stemerald_logs_worker:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /mnt/logs/worker
#
#  stemerald_db:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /mnt/database
