"""replace devide by ten with scale

Revision ID: 0528c4c627f9
Revises: 912786b01dd1
Create Date: 2019-03-26 11:51:38.704877

"""

# revision identifiers, used by Alembic.
revision = '0528c4c627f9'
down_revision = '912786b01dd1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


# FIXME: Default 0 value is bad idea

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('normalization_scale', sa.Integer(), nullable=False, default=0))
    op.add_column('currency', sa.Column('smallest_unit_scale', sa.Integer(), nullable=False, default=0))
    op.drop_column('currency', 'divide_by_ten')
    op.drop_column('market', 'divide_by_ten')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market', sa.Column('divide_by_ten', sa.INTEGER(), autoincrement=False, nullable=False, default=0))
    op.add_column('currency', sa.Column('divide_by_ten', sa.INTEGER(), autoincrement=False, nullable=False, default=0))
    op.drop_column('currency', 'smallest_unit_scale')
    op.drop_column('currency', 'normalization_scale')
    # ### end Alembic commands ###
