"""add wallet latest sync

Revision ID: 546013f4b282
Revises: 
Create Date: 2019-03-21 20:18:39.843534

"""

# revision identifiers, used by Alembic.
revision = '546013f4b282'
down_revision = '000000000000'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptocurrency', sa.Column('wallet_latest_sync', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptocurrency', 'wallet_latest_sync')
    # ### end Alembic commands ###
