# Use postgres/example user/password credentials
version: '3.6'

services:

  postgresql:
    container_name: postgresql_main
    image: stemerald/postgresql
    build: postgresql
    restart: always
    environment:
      DB_NAME: stemerald_db
      DB_USERNAME: stemerald
      DB_PASSWORD: stemerald
    networks:
      stemerald_net:
        ipv4_address: 192.168.19.44
    ports:
      - 65432:5432
#    volumes:
#      - stemerald_db:/var/lib/postgresql/data

  redis:
    container_name: redis_main
    image: stemerald/redis
    build: redis
    restart: always
    networks:
      stemerald_net:
        ipv4_address: 192.168.19.45
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - 6379


  service:
    container_name: service_main
    build:
      context: ..
      dockerfile: docker/service/Dockerfile
    restart: always
    depends_on:
      - postgresql
      - redis
    networks:
      stemerald_net:
        ipv4_address: 192.168.19.46
#    volumes:
#      - stemerald_logs_server:/var/log/stemerald
#      - stemerald_config:/etc/stemerald

  worker:
    container_name: worker_main
    build:
      context: ..
      dockerfile: docker/worker/Dockerfile
    restart: always
    depends_on:
      - postgresql
      - redis
      - service
    networks:
      stemerald_net:
        ipv4_address: 192.168.19.47
#    volumes:
#      - stemerald_logs_worker:/var/log/stemerald
#      - stemerald_config:/etc/stemerald


  cli:
    container_name: cli
    build: cli
    restart: always
    networks:
      stemerald_net:
        ipv4_address: 192.168.19.48
#    volumes:
#      - /var/stemerald/postgresql/master/data
#      - /var/stemerald/redis/master/lib
#      - /var/stemerald/service/log
#      - /var/stemerald/worker/log

networks:
  stemerald_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.19.0/24

volumes:
  stemerald_config:

#  stemerald_logs_server:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /mnt/logs/server
#
#  stemerald_logs_worker:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /mnt/logs/worker
#
#  stemerald_db:
#    driver: local-persist
#    driver_opts:
#      mountpoint: /mnt/database
